-- =============================================================================
-- Migration 096 — Module 3 of biz-onboarding roadmap: Approval email v2 + follow-up
-- =============================================================================
-- Per audit § Step 4 / Module 3. Tightens the post-approval flow:
--
--   1. businesses gains onboarding_call_* columns so we know:
--      - WHEN they booked their call (onboarding_call_booked_at)
--      - WHAT TIME the call is scheduled for (onboarding_call_at)
--      - WHICH BOOKING row backs it (onboarding_call_booking_id FK)
--
--   2. onboarding_bookings gains business_id so Rachel can see which biz a
--      booking belongs to (today she sees booker_email and a free-text
--      business_name field — fine for ad-hoc, broken once the email links to
--      ?biz=<slug>).
--
--   3. Rachel's host row is flipped from 30-min slots to 20-min slots
--      (Kenny's directive — see audit Step 4 finding 2). The page copy reads
--      host.slot_minutes so this single UPDATE is enough.
--
--   4. New view v_unbooked_approved_businesses surfaces approved-but-not-
--      booked rows >N days old. The onboarding-followup-cron EF queries this
--      view to decide who needs a nudge.
--
--   5. New table onboarding_followup_sends keeps an audit log of every nudge
--      sent so the cron doesn't email the same prospect twice in 7 days.
--
-- The book-onboarding-call.html page is updated alongside this migration to
-- read ?biz=<slug>, prefill the form, and set business_id on the booking.
-- =============================================================================

BEGIN;

-- ─── 1. businesses.onboarding_call_* columns ───────────────────────────────
ALTER TABLE public.businesses
    ADD COLUMN IF NOT EXISTS onboarding_call_booked_at  timestamptz,
    ADD COLUMN IF NOT EXISTS onboarding_call_at         timestamptz,
    ADD COLUMN IF NOT EXISTS onboarding_call_booking_id uuid;

-- We can't add the FK constraint via column shorthand because the column was
-- added IF NOT EXISTS; do it as a separate statement that's idempotent.
DO $add_fk$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'businesses_onboarding_call_booking_id_fkey'
    ) THEN
        ALTER TABLE public.businesses
            ADD CONSTRAINT businesses_onboarding_call_booking_id_fkey
            FOREIGN KEY (onboarding_call_booking_id)
            REFERENCES public.onboarding_bookings(id)
            ON DELETE SET NULL;
    END IF;
END $add_fk$;

COMMENT ON COLUMN public.businesses.onboarding_call_booked_at IS
  'Timestamp the prospect clicked through ?biz=<slug> on book-onboarding-call.html and confirmed a slot. NULL = they have not booked yet. Pairs with onboarding_call_at and onboarding_call_booking_id.';
COMMENT ON COLUMN public.businesses.onboarding_call_at IS
  'Start time of the scheduled onboarding call. Mirror of onboarding_bookings.starts_at for the linked booking; denormalized so we can query "calls coming up this week" without a join.';

-- ─── 2. onboarding_bookings.business_id ────────────────────────────────────
ALTER TABLE public.onboarding_bookings
    ADD COLUMN IF NOT EXISTS business_id uuid REFERENCES public.businesses(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS onboarding_bookings_business_idx
    ON public.onboarding_bookings(business_id)
    WHERE business_id IS NOT NULL;

COMMENT ON COLUMN public.onboarding_bookings.business_id IS
  'When the booker arrived via book-onboarding-call.html?biz=<slug>, this is the linked business. NULL for ad-hoc bookings (e.g. partners onboarding for themselves, or prospects who haven''t signed up the biz yet).';

-- ─── 3. Active onboarding hosts → 20-minute slots ──────────────────────────
-- Audit finding: Kenny wants 20-min, page hardcodes 30 (the hardcoded string
-- gets ripped out in this module's frontend change). The host row is the
-- source of truth; updating it here means every slot generated by
-- paintSlots() in book-onboarding-call.html is automatically 20-min wide.
--
-- The original 034 migration enforces `slot_minutes IN (15, 30, 45, 60)`. To
-- support 20-min calls without breaking any future host that prefers a
-- different cadence, expand the check constraint set to include 20.
ALTER TABLE public.onboarding_hosts
    DROP CONSTRAINT IF EXISTS onboarding_hosts_slot_minutes_check;
ALTER TABLE public.onboarding_hosts
    ADD  CONSTRAINT onboarding_hosts_slot_minutes_check
    CHECK (slot_minutes IN (10, 15, 20, 25, 30, 45, 60));

-- Note: schema uses `email` (NOT `contact_email`) on onboarding_hosts.
-- Today there's only one active host ("Founder / Admin" → Kenny). The audit
-- assumed a "Rachel" row, but Rachel hasn't been seeded yet — when she is,
-- her host row will inherit slot_minutes=20 from this UPDATE because we
-- target ALL active hosts, not just "Rachel" by name.
UPDATE public.onboarding_hosts
   SET slot_minutes = 20
 WHERE active = true
   AND slot_minutes <> 20;

-- ─── 4. v_unbooked_approved_businesses view ─────────────────────────────────
DROP VIEW IF EXISTS public.v_unbooked_approved_businesses CASCADE;
CREATE VIEW public.v_unbooked_approved_businesses
WITH (security_invoker = on)
AS
SELECT
    b.id,
    b.slug,
    b.display_name,
    b.legal_name,
    b.contact_email,
    b.contact_phone,
    b.owner_user_id,
    b.approved_at,
    b.approved_by,
    extract(epoch FROM (now() - b.approved_at))::int / 86400 AS days_since_approval,
    (
      SELECT count(*)::int
        FROM public.onboarding_followup_sends s
       WHERE s.business_id = b.id
    ) AS prior_nudges,
    (
      SELECT max(s.sent_at)
        FROM public.onboarding_followup_sends s
       WHERE s.business_id = b.id
    ) AS last_nudge_at
  FROM public.businesses b
 WHERE b.approval_status = 'approved'
   AND b.demo_only = false
   AND b.onboarding_call_booked_at IS NULL
   AND b.approved_at IS NOT NULL;

-- Wait — we reference onboarding_followup_sends inside the view, so it must
-- exist first. Restructure: create the table BEFORE the view. Done below.
COMMENT ON VIEW public.v_unbooked_approved_businesses IS
  'Approved businesses (not demo) that have not yet booked their onboarding call. Used by onboarding-followup-cron to decide who needs a nudge. days_since_approval drives the threshold; prior_nudges + last_nudge_at let the cron throttle.';

GRANT SELECT ON public.v_unbooked_approved_businesses TO authenticated;

-- ─── 5. onboarding_followup_sends — audit log of nudge emails ─────────────
CREATE TABLE IF NOT EXISTS public.onboarding_followup_sends (
    id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id           uuid NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    to_email              text NOT NULL,
    template_key          text NOT NULL DEFAULT 'onboarding_followup',
    days_since_approval   int  NOT NULL,
    sent_at               timestamptz NOT NULL DEFAULT now(),
    resend_message_id     text,
    error_text            text
);

CREATE INDEX IF NOT EXISTS onboarding_followup_sends_biz_idx
    ON public.onboarding_followup_sends(business_id, sent_at DESC);

ALTER TABLE public.onboarding_followup_sends ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS onboarding_followup_sends_admin_all ON public.onboarding_followup_sends;
CREATE POLICY onboarding_followup_sends_admin_all ON public.onboarding_followup_sends
    FOR ALL TO authenticated
    USING (public.am_i_admin())
    WITH CHECK (public.am_i_admin());

GRANT SELECT ON public.onboarding_followup_sends TO authenticated;

COMMENT ON TABLE public.onboarding_followup_sends IS
  'Audit log: every onboarding-followup nudge email we send. The cron consults this to enforce "no more than one nudge per business per 7 days" so prospects don''t get spammed.';

-- The view above references this table; recreate now that the table exists.
DROP VIEW IF EXISTS public.v_unbooked_approved_businesses CASCADE;
CREATE VIEW public.v_unbooked_approved_businesses
WITH (security_invoker = on)
AS
SELECT
    b.id,
    b.slug,
    b.display_name,
    b.legal_name,
    b.contact_email,
    b.contact_phone,
    b.owner_user_id,
    b.approved_at,
    b.approved_by,
    (extract(epoch FROM (now() - b.approved_at))::int / 86400) AS days_since_approval,
    (
      SELECT count(*)::int
        FROM public.onboarding_followup_sends s
       WHERE s.business_id = b.id
    ) AS prior_nudges,
    (
      SELECT max(s.sent_at)
        FROM public.onboarding_followup_sends s
       WHERE s.business_id = b.id
    ) AS last_nudge_at
  FROM public.businesses b
 WHERE b.approval_status = 'approved'
   AND b.demo_only = false
   AND b.onboarding_call_booked_at IS NULL
   AND b.approved_at IS NOT NULL;

GRANT SELECT ON public.v_unbooked_approved_businesses TO authenticated;

-- ─── 6. fn_mark_onboarding_booking_for_business RPC ─────────────────────────
-- Called by the book-onboarding-call.html page right after the booking insert
-- succeeds AND the URL contained ?biz=<slug>. Server-side gate prevents anon
-- from arbitrarily marking biz rows: it only succeeds if the booking's
-- business_id matches the biz looked up by slug AND the booking row was
-- created in the last 5 minutes (so anyone can use this immediately after
-- their own booking but it can't be replayed).
CREATE OR REPLACE FUNCTION public.fn_mark_onboarding_booking_for_business(
    p_booking_id uuid,
    p_biz_slug   text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $mark_booking$
DECLARE
    v_bk public.onboarding_bookings%ROWTYPE;
    v_biz public.businesses%ROWTYPE;
BEGIN
    IF p_booking_id IS NULL OR p_biz_slug IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'missing_args');
    END IF;

    SELECT * INTO v_bk FROM public.onboarding_bookings WHERE id = p_booking_id;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'booking_not_found');
    END IF;
    -- Freshness gate
    IF v_bk.created_at < now() - interval '5 minutes' THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'booking_too_old');
    END IF;

    SELECT * INTO v_biz FROM public.businesses WHERE slug = p_biz_slug;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'business_not_found');
    END IF;

    -- Link the booking → business
    UPDATE public.onboarding_bookings
       SET business_id = v_biz.id
     WHERE id = v_bk.id;

    -- Mirror to businesses
    UPDATE public.businesses
       SET onboarding_call_booked_at  = COALESCE(onboarding_call_booked_at, now()),
           onboarding_call_at         = v_bk.starts_at,
           onboarding_call_booking_id = v_bk.id
     WHERE id = v_biz.id;

    RETURN jsonb_build_object(
        'ok',          true,
        'booking_id',  v_bk.id,
        'business_id', v_biz.id,
        'slug',        v_biz.slug,
        'starts_at',   v_bk.starts_at
    );
END $mark_booking$;

GRANT EXECUTE ON FUNCTION public.fn_mark_onboarding_booking_for_business(uuid, text) TO anon, authenticated, service_role;

COMMENT ON FUNCTION public.fn_mark_onboarding_booking_for_business(uuid, text) IS
  'Anon-callable RPC: marks a freshly-created onboarding booking as belonging to a business (via slug). Guarded by a 5-minute freshness window on the booking row so replay attacks can''t link arbitrary bookings to arbitrary businesses. Called by book-onboarding-call.html?biz=<slug> immediately after the booking insert succeeds.';

-- ─── 7. Sanity output ──────────────────────────────────────────────────────
DO $sanity_096$
DECLARE
    v_biz_cols     int;
    v_book_col     boolean;
    v_view_exists  boolean;
    v_log_exists   boolean;
    v_rpc_exists   boolean;
    v_rachel_slot  int;
BEGIN
    SELECT count(*) FROM information_schema.columns
     WHERE table_schema='public' AND table_name='businesses'
       AND column_name IN ('onboarding_call_booked_at','onboarding_call_at','onboarding_call_booking_id')
    INTO v_biz_cols;

    SELECT EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema='public' AND table_name='onboarding_bookings'
           AND column_name='business_id'
    ) INTO v_book_col;

    SELECT EXISTS (
        SELECT 1 FROM information_schema.views
         WHERE table_schema='public' AND table_name='v_unbooked_approved_businesses'
    ) INTO v_view_exists;

    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables
         WHERE table_schema='public' AND table_name='onboarding_followup_sends'
    ) INTO v_log_exists;

    SELECT EXISTS (
        SELECT 1 FROM pg_proc WHERE proname='fn_mark_onboarding_booking_for_business'
    ) INTO v_rpc_exists;

    SELECT max(slot_minutes) FROM public.onboarding_hosts
     WHERE active = true
    INTO v_rachel_slot;

    RAISE NOTICE 'Module 3 migration 096: biz_cols=%/3 booking_col=% view=% log=% rpc=% rachel_slot_min=%',
        v_biz_cols, v_book_col, v_view_exists, v_log_exists, v_rpc_exists, v_rachel_slot;

    IF v_biz_cols <> 3 THEN
        RAISE EXCEPTION 'Migration 096 failed: expected 3 new biz cols, got %', v_biz_cols;
    END IF;
    IF NOT v_book_col THEN
        RAISE EXCEPTION 'Migration 096 failed: onboarding_bookings.business_id did not create';
    END IF;
    IF NOT v_view_exists THEN
        RAISE EXCEPTION 'Migration 096 failed: v_unbooked_approved_businesses did not create';
    END IF;
END $sanity_096$;

COMMIT;
